service: ponto-demo

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
      Resource: arn:aws:sqs:us-east-1:619549927047:PontoRequests

functions:
  dequeue:
    handler: handler.dequeue
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:619549927047:PontoRequests
          batchSize: 1

  enqueue:
    handler: handler.enqueue
    events:
      - http: GET ponto
